---
- name: Installing nginx on master
  hosts: node2
  become: true 
  tasks: 
  - name: Install common services 
    import_tasks: ./tasks/install-common-service.yaml
    when: false 
  - name: Uninstall common services 
    import_tasks: ./tasks/remove-common-service.yaml 